CREATE TABLE TBL_PRODUCT (
	PNO NUMBER,
	TITLE VARCHAR2(200) NOT NULL,
	CONTENT VARCHAR2(2000) NOT NULL,
	WRITER VARCHAR2(100) NOT NULL,
	REGD8 DATE DEFAULT sysdate,
	MODD8 DATE DEFAULT sysdate,
	READCOUNT NUMBER DEFAULT 0,
	IMGFILE VARCHAR2(2000)
);
ALTER TABLE TBL_PRODUCT 
ADD CONSTRAINT TBL_PRODUCT_PK PRIMARY KEY (PNO)
ENABLE;
CREATE SEQUENCE SEQ_PRODUCT INCREMENT BY 1 MINVALUE 0 NOCYCLE NOCACHE NOORDER ;

CREATE TABLE TBL_NOTICE (
	NUM NUMBER NOT NULL,
	TITLE VARCHAR2(200) NOT NULL,
	WRITER VARCHAR2(100) NOT NULL,
	CONTENT VARCHAR2(2000) NOT NULL,
	REGDATE DATE DEFAULT sysdate,
	MODDATE DATE DEFAULT sysdate,
	READCOUNT NUMBER DEFAULT 0,
	IMGFILE VARCHAR2(2000)
);

ALTER TABLE SPRINGDB.TBL_NOTICE
ADD CONSTRAINT TBL_NOTICE_PK PRIMARY KEY (NUM)
ENABLE;
CREATE SEQUENCE SEQ_NOTICE INCREMENT BY 1 MINVALUE 0 NOCYCLE NOCACHE NOORDER ;




  CREATE TABLE "SPRINGDB"."TBL_LOCATION" 
   (   "PNO" NUMBER(22,127) NOT NULL ENABLE, 
   "PNAME" VARCHAR2(600), 
   "PLAT" NUMBER, 
   "PLNG" NUMBER, 
   "ADDR" VARCHAR2(1000), 
   "CTIME" CHAR(1) DEFAULT 0 NOT NULL ENABLE, 
   "PHONE" VARCHAR2(100), 
   "ROADADDR" VARCHAR2(100)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;




CREATE TABLE TBL_MEMBER (
	USERNUM NUMBER NOT NULL,
	USERID VARCHAR2(100) NOT NULL,
	PASSOWRD VARCHAR2(200) NOT NULL,
	EMAIL VARCHAR2(200) NOT NULL,
	AUTHORITY NUMBER DEFAULT 0,
	REGD8 DATE DEFAULT sysdate
);
ALTER TABLE SPRINGDB.TBL_MEMBER
ADD CONSTRAINT TBL_MEMBER_PK PRIMARY KEY (USERNUM)
ENABLE;
CREATE SEQUENCE SPRINGDB.SEQ_MEMBER INCREMENT BY 1 MINVALUE 0 NOCYCLE NOCACHE NOORDER ;

